site_name: BobbyX-Dev's Blog, Documentation, Wiki and more!
nav:
  - Home: index.md
  - blog:
    - Linux > Windows: post001.md
    - Test: post002.md
  - About: about.md

theme:
  name: material
  user_color_mode_toggle: true
  palette:
    scheme: slate

plugins:
  - search
  - blog